/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ServicioDeMantencionDeAreasVerdesRouteImport } from './routes/servicio-de-mantencion-de-areas-verdes'
import { Route as ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRouteImport } from './routes/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
import { Route as ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRouteImport } from './routes/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
import { Route as ProyectoPaisajismoResidencialZapallarChileRouteImport } from './routes/proyecto-paisajismo-residencial-zapallar-chile'
import { Route as ProyectoPaisajismoRouteImport } from './routes/proyecto-paisajismo'
import { Route as ProyectoMuroVerdeVerticalVitacuraChileRouteImport } from './routes/proyecto-muro-verde-vertical-vitacura-chile'
import { Route as ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRouteImport } from './routes/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
import { Route as ProyectoHabilitacionTerrazaCorporativaLasCondesChileRouteImport } from './routes/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
import { Route as ProyectoFumigacionControlFitosanitarioQuilicuraChileRouteImport } from './routes/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
import { Route as ProyectoDisenoPaisajismoVialCopecSantiagoChileRouteImport } from './routes/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
import { Route as ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRouteImport } from './routes/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
import { Route as PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRouteImport } from './routes/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
import { Route as GlosarioRouteImport } from './routes/glosario'
import { Route as DisenoYConstrucionDeSistemasDeRiegoRouteImport } from './routes/diseno-y-construcion-de-sistemas-de-riego'
import { Route as DisenoYConstruccionDeAreasVerdesRouteImport } from './routes/diseno-y-construccion-de-areas-verdes'
import { Route as ControlFitosanitarioYManejoDePlagasAreasVerdesRouteImport } from './routes/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as TrabajoPodaTalaEmergenciaAraucoQuilicuraRouteImport } from './routes/Trabajo-poda-tala-emergencia-arauco-quilicura'
import { Route as TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRouteImport } from './routes/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura'
import { Route as TrabajoMovimientoMacetasQuilicuraRouteImport } from './routes/Trabajo-movimiento-macetas-quilicura'
import { Route as TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRouteImport } from './routes/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura'
import { Route as TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRouteImport } from './routes/Trabajo-despeje-canal-arauco-san-ignacio-quilicura'
import { Route as TrabajoDelimitadorVegetalExteriorMallQuilicuraRouteImport } from './routes/Trabajo-delimitador-vegetal-exterior-mall-quilicura'
import { Route as PodaEmergenciaEmpresaAirLiquideRouteImport } from './routes/Poda-emergencia-empresa-air-liquide'
import { Route as PaisajismoJardineraPalletMallQuilicuraRouteImport } from './routes/Paisajismo-jardinera-pallet-mall-quilicura'
import { Route as MantencionPreventivaContratoAnualAraucoQuilicuraRouteImport } from './routes/Mantencion-preventiva-contrato-anual-arauco-quilicura'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfoIndexRouteImport } from './routes/info/index'
import { Route as InfoXerojardineriaPaisajismoSecoCorporativoRouteImport } from './routes/info/xerojardineria-paisajismo-seco-corporativo'
import { Route as InfoMurosVerdesYJardinesVerticalesCorporativosRouteImport } from './routes/info/muros-verdes-y-jardines-verticales-corporativos'
import { Route as InfoImportanciaRiegoInteligenteEmpresasRouteImport } from './routes/info/importancia-riego-inteligente-empresas'
import { Route as InfoImportanciaPodaPreventivaOtonoRouteImport } from './routes/info/importancia-poda-preventiva-otono'
import { Route as InfoImportanciaFumigacionesPreventivasRouteImport } from './routes/info/importancia-fumigaciones-preventivas'
import { Route as InfoImportanciaDesmalezadoControlPlagasEmpresasRouteImport } from './routes/info/importancia-desmalezado-control-plagas-empresas'
import { Route as InfoImportanciaDeAreasVerdesOficinasEmpresasRouteImport } from './routes/info/importancia-de-areas-verdes-oficinas-empresas'
import { Route as InfoEndoterapiaVegetalAlternativaEcologicaRouteImport } from './routes/info/endoterapia-vegetal-alternativa-ecologica'
import { Route as InfoBeneficiosDisenoBiofilicoProductividadRouteImport } from './routes/info/beneficios-diseno-biofilico-productividad'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicioDeMantencionDeAreasVerdesRoute =
  ServicioDeMantencionDeAreasVerdesRouteImport.update({
    id: '/servicio-de-mantencion-de-areas-verdes',
    path: '/servicio-de-mantencion-de-areas-verdes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute =
  ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRouteImport.update({
    id: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile',
    path: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute =
  ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRouteImport.update({
    id: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile',
    path: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoPaisajismoResidencialZapallarChileRoute =
  ProyectoPaisajismoResidencialZapallarChileRouteImport.update({
    id: '/proyecto-paisajismo-residencial-zapallar-chile',
    path: '/proyecto-paisajismo-residencial-zapallar-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoPaisajismoRoute = ProyectoPaisajismoRouteImport.update({
  id: '/proyecto-paisajismo',
  path: '/proyecto-paisajismo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoMuroVerdeVerticalVitacuraChileRoute =
  ProyectoMuroVerdeVerticalVitacuraChileRouteImport.update({
    id: '/proyecto-muro-verde-vertical-vitacura-chile',
    path: '/proyecto-muro-verde-vertical-vitacura-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute =
  ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRouteImport.update({
    id: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile',
    path: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute =
  ProyectoHabilitacionTerrazaCorporativaLasCondesChileRouteImport.update({
    id: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile',
    path: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute =
  ProyectoFumigacionControlFitosanitarioQuilicuraChileRouteImport.update({
    id: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile',
    path: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute =
  ProyectoDisenoPaisajismoVialCopecSantiagoChileRouteImport.update({
    id: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile',
    path: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute =
  ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRouteImport.update({
    id: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile',
    path: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute =
  PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRouteImport.update({
    id: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial',
    path: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial',
    getParentRoute: () => rootRouteImport,
  } as any)
const GlosarioRoute = GlosarioRouteImport.update({
  id: '/glosario',
  path: '/glosario',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoYConstrucionDeSistemasDeRiegoRoute =
  DisenoYConstrucionDeSistemasDeRiegoRouteImport.update({
    id: '/diseno-y-construcion-de-sistemas-de-riego',
    path: '/diseno-y-construcion-de-sistemas-de-riego',
    getParentRoute: () => rootRouteImport,
  } as any)
const DisenoYConstruccionDeAreasVerdesRoute =
  DisenoYConstruccionDeAreasVerdesRouteImport.update({
    id: '/diseno-y-construccion-de-areas-verdes',
    path: '/diseno-y-construccion-de-areas-verdes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ControlFitosanitarioYManejoDePlagasAreasVerdesRoute =
  ControlFitosanitarioYManejoDePlagasAreasVerdesRouteImport.update({
    id: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes',
    path: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajoPodaTalaEmergenciaAraucoQuilicuraRoute =
  TrabajoPodaTalaEmergenciaAraucoQuilicuraRouteImport.update({
    id: '/Trabajo-poda-tala-emergencia-arauco-quilicura',
    path: '/Trabajo-poda-tala-emergencia-arauco-quilicura',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRoute =
  TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRouteImport.update({
    id: '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura',
    path: '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrabajoMovimientoMacetasQuilicuraRoute =
  TrabajoMovimientoMacetasQuilicuraRouteImport.update({
    id: '/Trabajo-movimiento-macetas-quilicura',
    path: '/Trabajo-movimiento-macetas-quilicura',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRoute =
  TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRouteImport.update({
    id: '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura',
    path: '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRoute =
  TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRouteImport.update({
    id: '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura',
    path: '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrabajoDelimitadorVegetalExteriorMallQuilicuraRoute =
  TrabajoDelimitadorVegetalExteriorMallQuilicuraRouteImport.update({
    id: '/Trabajo-delimitador-vegetal-exterior-mall-quilicura',
    path: '/Trabajo-delimitador-vegetal-exterior-mall-quilicura',
    getParentRoute: () => rootRouteImport,
  } as any)
const PodaEmergenciaEmpresaAirLiquideRoute =
  PodaEmergenciaEmpresaAirLiquideRouteImport.update({
    id: '/Poda-emergencia-empresa-air-liquide',
    path: '/Poda-emergencia-empresa-air-liquide',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaisajismoJardineraPalletMallQuilicuraRoute =
  PaisajismoJardineraPalletMallQuilicuraRouteImport.update({
    id: '/Paisajismo-jardinera-pallet-mall-quilicura',
    path: '/Paisajismo-jardinera-pallet-mall-quilicura',
    getParentRoute: () => rootRouteImport,
  } as any)
const MantencionPreventivaContratoAnualAraucoQuilicuraRoute =
  MantencionPreventivaContratoAnualAraucoQuilicuraRouteImport.update({
    id: '/Mantencion-preventiva-contrato-anual-arauco-quilicura',
    path: '/Mantencion-preventiva-contrato-anual-arauco-quilicura',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoIndexRoute = InfoIndexRouteImport.update({
  id: '/info/',
  path: '/info/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoXerojardineriaPaisajismoSecoCorporativoRoute =
  InfoXerojardineriaPaisajismoSecoCorporativoRouteImport.update({
    id: '/info/xerojardineria-paisajismo-seco-corporativo',
    path: '/info/xerojardineria-paisajismo-seco-corporativo',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoMurosVerdesYJardinesVerticalesCorporativosRoute =
  InfoMurosVerdesYJardinesVerticalesCorporativosRouteImport.update({
    id: '/info/muros-verdes-y-jardines-verticales-corporativos',
    path: '/info/muros-verdes-y-jardines-verticales-corporativos',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoImportanciaRiegoInteligenteEmpresasRoute =
  InfoImportanciaRiegoInteligenteEmpresasRouteImport.update({
    id: '/info/importancia-riego-inteligente-empresas',
    path: '/info/importancia-riego-inteligente-empresas',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoImportanciaPodaPreventivaOtonoRoute =
  InfoImportanciaPodaPreventivaOtonoRouteImport.update({
    id: '/info/importancia-poda-preventiva-otono',
    path: '/info/importancia-poda-preventiva-otono',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoImportanciaFumigacionesPreventivasRoute =
  InfoImportanciaFumigacionesPreventivasRouteImport.update({
    id: '/info/importancia-fumigaciones-preventivas',
    path: '/info/importancia-fumigaciones-preventivas',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoImportanciaDesmalezadoControlPlagasEmpresasRoute =
  InfoImportanciaDesmalezadoControlPlagasEmpresasRouteImport.update({
    id: '/info/importancia-desmalezado-control-plagas-empresas',
    path: '/info/importancia-desmalezado-control-plagas-empresas',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoImportanciaDeAreasVerdesOficinasEmpresasRoute =
  InfoImportanciaDeAreasVerdesOficinasEmpresasRouteImport.update({
    id: '/info/importancia-de-areas-verdes-oficinas-empresas',
    path: '/info/importancia-de-areas-verdes-oficinas-empresas',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoEndoterapiaVegetalAlternativaEcologicaRoute =
  InfoEndoterapiaVegetalAlternativaEcologicaRouteImport.update({
    id: '/info/endoterapia-vegetal-alternativa-ecologica',
    path: '/info/endoterapia-vegetal-alternativa-ecologica',
    getParentRoute: () => rootRouteImport,
  } as any)
const InfoBeneficiosDisenoBiofilicoProductividadRoute =
  InfoBeneficiosDisenoBiofilicoProductividadRouteImport.update({
    id: '/info/beneficios-diseno-biofilico-productividad',
    path: '/info/beneficios-diseno-biofilico-productividad',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Mantencion-preventiva-contrato-anual-arauco-quilicura': typeof MantencionPreventivaContratoAnualAraucoQuilicuraRoute
  '/Paisajismo-jardinera-pallet-mall-quilicura': typeof PaisajismoJardineraPalletMallQuilicuraRoute
  '/Poda-emergencia-empresa-air-liquide': typeof PodaEmergenciaEmpresaAirLiquideRoute
  '/Trabajo-delimitador-vegetal-exterior-mall-quilicura': typeof TrabajoDelimitadorVegetalExteriorMallQuilicuraRoute
  '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura': typeof TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura': typeof TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-movimiento-macetas-quilicura': typeof TrabajoMovimientoMacetasQuilicuraRoute
  '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura': typeof TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-poda-tala-emergencia-arauco-quilicura': typeof TrabajoPodaTalaEmergenciaAraucoQuilicuraRoute
  '/contacto': typeof ContactoRoute
  '/control-fitosanitario-y-manejo-de-plagas-areas-verdes': typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRoute
  '/diseno-y-construccion-de-areas-verdes': typeof DisenoYConstruccionDeAreasVerdesRoute
  '/diseno-y-construcion-de-sistemas-de-riego': typeof DisenoYConstrucionDeSistemasDeRiegoRoute
  '/glosario': typeof GlosarioRoute
  '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial': typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute
  '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile': typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute
  '/proyecto-diseno-paisajismo-vial-copec-santiago-chile': typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute
  '/proyecto-fumigacion-control-fitosanitario-quilicura-chile': typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute
  '/proyecto-habilitacion-terraza-corporativa-las-condes-chile': typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute
  '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile': typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute
  '/proyecto-muro-verde-vertical-vitacura-chile': typeof ProyectoMuroVerdeVerticalVitacuraChileRoute
  '/proyecto-paisajismo': typeof ProyectoPaisajismoRoute
  '/proyecto-paisajismo-residencial-zapallar-chile': typeof ProyectoPaisajismoResidencialZapallarChileRoute
  '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile': typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute
  '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile': typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute
  '/servicio-de-mantencion-de-areas-verdes': typeof ServicioDeMantencionDeAreasVerdesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/info/beneficios-diseno-biofilico-productividad': typeof InfoBeneficiosDisenoBiofilicoProductividadRoute
  '/info/endoterapia-vegetal-alternativa-ecologica': typeof InfoEndoterapiaVegetalAlternativaEcologicaRoute
  '/info/importancia-de-areas-verdes-oficinas-empresas': typeof InfoImportanciaDeAreasVerdesOficinasEmpresasRoute
  '/info/importancia-desmalezado-control-plagas-empresas': typeof InfoImportanciaDesmalezadoControlPlagasEmpresasRoute
  '/info/importancia-fumigaciones-preventivas': typeof InfoImportanciaFumigacionesPreventivasRoute
  '/info/importancia-poda-preventiva-otono': typeof InfoImportanciaPodaPreventivaOtonoRoute
  '/info/importancia-riego-inteligente-empresas': typeof InfoImportanciaRiegoInteligenteEmpresasRoute
  '/info/muros-verdes-y-jardines-verticales-corporativos': typeof InfoMurosVerdesYJardinesVerticalesCorporativosRoute
  '/info/xerojardineria-paisajismo-seco-corporativo': typeof InfoXerojardineriaPaisajismoSecoCorporativoRoute
  '/info/': typeof InfoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Mantencion-preventiva-contrato-anual-arauco-quilicura': typeof MantencionPreventivaContratoAnualAraucoQuilicuraRoute
  '/Paisajismo-jardinera-pallet-mall-quilicura': typeof PaisajismoJardineraPalletMallQuilicuraRoute
  '/Poda-emergencia-empresa-air-liquide': typeof PodaEmergenciaEmpresaAirLiquideRoute
  '/Trabajo-delimitador-vegetal-exterior-mall-quilicura': typeof TrabajoDelimitadorVegetalExteriorMallQuilicuraRoute
  '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura': typeof TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura': typeof TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-movimiento-macetas-quilicura': typeof TrabajoMovimientoMacetasQuilicuraRoute
  '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura': typeof TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-poda-tala-emergencia-arauco-quilicura': typeof TrabajoPodaTalaEmergenciaAraucoQuilicuraRoute
  '/contacto': typeof ContactoRoute
  '/control-fitosanitario-y-manejo-de-plagas-areas-verdes': typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRoute
  '/diseno-y-construccion-de-areas-verdes': typeof DisenoYConstruccionDeAreasVerdesRoute
  '/diseno-y-construcion-de-sistemas-de-riego': typeof DisenoYConstrucionDeSistemasDeRiegoRoute
  '/glosario': typeof GlosarioRoute
  '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial': typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute
  '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile': typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute
  '/proyecto-diseno-paisajismo-vial-copec-santiago-chile': typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute
  '/proyecto-fumigacion-control-fitosanitario-quilicura-chile': typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute
  '/proyecto-habilitacion-terraza-corporativa-las-condes-chile': typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute
  '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile': typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute
  '/proyecto-muro-verde-vertical-vitacura-chile': typeof ProyectoMuroVerdeVerticalVitacuraChileRoute
  '/proyecto-paisajismo': typeof ProyectoPaisajismoRoute
  '/proyecto-paisajismo-residencial-zapallar-chile': typeof ProyectoPaisajismoResidencialZapallarChileRoute
  '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile': typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute
  '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile': typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute
  '/servicio-de-mantencion-de-areas-verdes': typeof ServicioDeMantencionDeAreasVerdesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/info/beneficios-diseno-biofilico-productividad': typeof InfoBeneficiosDisenoBiofilicoProductividadRoute
  '/info/endoterapia-vegetal-alternativa-ecologica': typeof InfoEndoterapiaVegetalAlternativaEcologicaRoute
  '/info/importancia-de-areas-verdes-oficinas-empresas': typeof InfoImportanciaDeAreasVerdesOficinasEmpresasRoute
  '/info/importancia-desmalezado-control-plagas-empresas': typeof InfoImportanciaDesmalezadoControlPlagasEmpresasRoute
  '/info/importancia-fumigaciones-preventivas': typeof InfoImportanciaFumigacionesPreventivasRoute
  '/info/importancia-poda-preventiva-otono': typeof InfoImportanciaPodaPreventivaOtonoRoute
  '/info/importancia-riego-inteligente-empresas': typeof InfoImportanciaRiegoInteligenteEmpresasRoute
  '/info/muros-verdes-y-jardines-verticales-corporativos': typeof InfoMurosVerdesYJardinesVerticalesCorporativosRoute
  '/info/xerojardineria-paisajismo-seco-corporativo': typeof InfoXerojardineriaPaisajismoSecoCorporativoRoute
  '/info': typeof InfoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Mantencion-preventiva-contrato-anual-arauco-quilicura': typeof MantencionPreventivaContratoAnualAraucoQuilicuraRoute
  '/Paisajismo-jardinera-pallet-mall-quilicura': typeof PaisajismoJardineraPalletMallQuilicuraRoute
  '/Poda-emergencia-empresa-air-liquide': typeof PodaEmergenciaEmpresaAirLiquideRoute
  '/Trabajo-delimitador-vegetal-exterior-mall-quilicura': typeof TrabajoDelimitadorVegetalExteriorMallQuilicuraRoute
  '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura': typeof TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura': typeof TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-movimiento-macetas-quilicura': typeof TrabajoMovimientoMacetasQuilicuraRoute
  '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura': typeof TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRoute
  '/Trabajo-poda-tala-emergencia-arauco-quilicura': typeof TrabajoPodaTalaEmergenciaAraucoQuilicuraRoute
  '/contacto': typeof ContactoRoute
  '/control-fitosanitario-y-manejo-de-plagas-areas-verdes': typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRoute
  '/diseno-y-construccion-de-areas-verdes': typeof DisenoYConstruccionDeAreasVerdesRoute
  '/diseno-y-construcion-de-sistemas-de-riego': typeof DisenoYConstrucionDeSistemasDeRiegoRoute
  '/glosario': typeof GlosarioRoute
  '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial': typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute
  '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile': typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute
  '/proyecto-diseno-paisajismo-vial-copec-santiago-chile': typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute
  '/proyecto-fumigacion-control-fitosanitario-quilicura-chile': typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute
  '/proyecto-habilitacion-terraza-corporativa-las-condes-chile': typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute
  '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile': typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute
  '/proyecto-muro-verde-vertical-vitacura-chile': typeof ProyectoMuroVerdeVerticalVitacuraChileRoute
  '/proyecto-paisajismo': typeof ProyectoPaisajismoRoute
  '/proyecto-paisajismo-residencial-zapallar-chile': typeof ProyectoPaisajismoResidencialZapallarChileRoute
  '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile': typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute
  '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile': typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute
  '/servicio-de-mantencion-de-areas-verdes': typeof ServicioDeMantencionDeAreasVerdesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/info/beneficios-diseno-biofilico-productividad': typeof InfoBeneficiosDisenoBiofilicoProductividadRoute
  '/info/endoterapia-vegetal-alternativa-ecologica': typeof InfoEndoterapiaVegetalAlternativaEcologicaRoute
  '/info/importancia-de-areas-verdes-oficinas-empresas': typeof InfoImportanciaDeAreasVerdesOficinasEmpresasRoute
  '/info/importancia-desmalezado-control-plagas-empresas': typeof InfoImportanciaDesmalezadoControlPlagasEmpresasRoute
  '/info/importancia-fumigaciones-preventivas': typeof InfoImportanciaFumigacionesPreventivasRoute
  '/info/importancia-poda-preventiva-otono': typeof InfoImportanciaPodaPreventivaOtonoRoute
  '/info/importancia-riego-inteligente-empresas': typeof InfoImportanciaRiegoInteligenteEmpresasRoute
  '/info/muros-verdes-y-jardines-verticales-corporativos': typeof InfoMurosVerdesYJardinesVerticalesCorporativosRoute
  '/info/xerojardineria-paisajismo-seco-corporativo': typeof InfoXerojardineriaPaisajismoSecoCorporativoRoute
  '/info/': typeof InfoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Mantencion-preventiva-contrato-anual-arauco-quilicura'
    | '/Paisajismo-jardinera-pallet-mall-quilicura'
    | '/Poda-emergencia-empresa-air-liquide'
    | '/Trabajo-delimitador-vegetal-exterior-mall-quilicura'
    | '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura'
    | '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura'
    | '/Trabajo-movimiento-macetas-quilicura'
    | '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura'
    | '/Trabajo-poda-tala-emergencia-arauco-quilicura'
    | '/contacto'
    | '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
    | '/diseno-y-construccion-de-areas-verdes'
    | '/diseno-y-construcion-de-sistemas-de-riego'
    | '/glosario'
    | '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
    | '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
    | '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
    | '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
    | '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
    | '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
    | '/proyecto-muro-verde-vertical-vitacura-chile'
    | '/proyecto-paisajismo'
    | '/proyecto-paisajismo-residencial-zapallar-chile'
    | '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
    | '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
    | '/servicio-de-mantencion-de-areas-verdes'
    | '/sobre-nosotros'
    | '/info/beneficios-diseno-biofilico-productividad'
    | '/info/endoterapia-vegetal-alternativa-ecologica'
    | '/info/importancia-de-areas-verdes-oficinas-empresas'
    | '/info/importancia-desmalezado-control-plagas-empresas'
    | '/info/importancia-fumigaciones-preventivas'
    | '/info/importancia-poda-preventiva-otono'
    | '/info/importancia-riego-inteligente-empresas'
    | '/info/muros-verdes-y-jardines-verticales-corporativos'
    | '/info/xerojardineria-paisajismo-seco-corporativo'
    | '/info/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Mantencion-preventiva-contrato-anual-arauco-quilicura'
    | '/Paisajismo-jardinera-pallet-mall-quilicura'
    | '/Poda-emergencia-empresa-air-liquide'
    | '/Trabajo-delimitador-vegetal-exterior-mall-quilicura'
    | '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura'
    | '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura'
    | '/Trabajo-movimiento-macetas-quilicura'
    | '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura'
    | '/Trabajo-poda-tala-emergencia-arauco-quilicura'
    | '/contacto'
    | '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
    | '/diseno-y-construccion-de-areas-verdes'
    | '/diseno-y-construcion-de-sistemas-de-riego'
    | '/glosario'
    | '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
    | '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
    | '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
    | '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
    | '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
    | '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
    | '/proyecto-muro-verde-vertical-vitacura-chile'
    | '/proyecto-paisajismo'
    | '/proyecto-paisajismo-residencial-zapallar-chile'
    | '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
    | '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
    | '/servicio-de-mantencion-de-areas-verdes'
    | '/sobre-nosotros'
    | '/info/beneficios-diseno-biofilico-productividad'
    | '/info/endoterapia-vegetal-alternativa-ecologica'
    | '/info/importancia-de-areas-verdes-oficinas-empresas'
    | '/info/importancia-desmalezado-control-plagas-empresas'
    | '/info/importancia-fumigaciones-preventivas'
    | '/info/importancia-poda-preventiva-otono'
    | '/info/importancia-riego-inteligente-empresas'
    | '/info/muros-verdes-y-jardines-verticales-corporativos'
    | '/info/xerojardineria-paisajismo-seco-corporativo'
    | '/info'
  id:
    | '__root__'
    | '/'
    | '/Mantencion-preventiva-contrato-anual-arauco-quilicura'
    | '/Paisajismo-jardinera-pallet-mall-quilicura'
    | '/Poda-emergencia-empresa-air-liquide'
    | '/Trabajo-delimitador-vegetal-exterior-mall-quilicura'
    | '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura'
    | '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura'
    | '/Trabajo-movimiento-macetas-quilicura'
    | '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura'
    | '/Trabajo-poda-tala-emergencia-arauco-quilicura'
    | '/contacto'
    | '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
    | '/diseno-y-construccion-de-areas-verdes'
    | '/diseno-y-construcion-de-sistemas-de-riego'
    | '/glosario'
    | '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
    | '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
    | '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
    | '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
    | '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
    | '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
    | '/proyecto-muro-verde-vertical-vitacura-chile'
    | '/proyecto-paisajismo'
    | '/proyecto-paisajismo-residencial-zapallar-chile'
    | '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
    | '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
    | '/servicio-de-mantencion-de-areas-verdes'
    | '/sobre-nosotros'
    | '/info/beneficios-diseno-biofilico-productividad'
    | '/info/endoterapia-vegetal-alternativa-ecologica'
    | '/info/importancia-de-areas-verdes-oficinas-empresas'
    | '/info/importancia-desmalezado-control-plagas-empresas'
    | '/info/importancia-fumigaciones-preventivas'
    | '/info/importancia-poda-preventiva-otono'
    | '/info/importancia-riego-inteligente-empresas'
    | '/info/muros-verdes-y-jardines-verticales-corporativos'
    | '/info/xerojardineria-paisajismo-seco-corporativo'
    | '/info/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MantencionPreventivaContratoAnualAraucoQuilicuraRoute: typeof MantencionPreventivaContratoAnualAraucoQuilicuraRoute
  PaisajismoJardineraPalletMallQuilicuraRoute: typeof PaisajismoJardineraPalletMallQuilicuraRoute
  PodaEmergenciaEmpresaAirLiquideRoute: typeof PodaEmergenciaEmpresaAirLiquideRoute
  TrabajoDelimitadorVegetalExteriorMallQuilicuraRoute: typeof TrabajoDelimitadorVegetalExteriorMallQuilicuraRoute
  TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRoute: typeof TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRoute
  TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRoute: typeof TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRoute
  TrabajoMovimientoMacetasQuilicuraRoute: typeof TrabajoMovimientoMacetasQuilicuraRoute
  TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRoute: typeof TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRoute
  TrabajoPodaTalaEmergenciaAraucoQuilicuraRoute: typeof TrabajoPodaTalaEmergenciaAraucoQuilicuraRoute
  ContactoRoute: typeof ContactoRoute
  ControlFitosanitarioYManejoDePlagasAreasVerdesRoute: typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRoute
  DisenoYConstruccionDeAreasVerdesRoute: typeof DisenoYConstruccionDeAreasVerdesRoute
  DisenoYConstrucionDeSistemasDeRiegoRoute: typeof DisenoYConstrucionDeSistemasDeRiegoRoute
  GlosarioRoute: typeof GlosarioRoute
  PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute: typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute
  ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute: typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute
  ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute: typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute
  ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute: typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute
  ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute: typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute
  ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute: typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute
  ProyectoMuroVerdeVerticalVitacuraChileRoute: typeof ProyectoMuroVerdeVerticalVitacuraChileRoute
  ProyectoPaisajismoRoute: typeof ProyectoPaisajismoRoute
  ProyectoPaisajismoResidencialZapallarChileRoute: typeof ProyectoPaisajismoResidencialZapallarChileRoute
  ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute: typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute
  ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute: typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute
  ServicioDeMantencionDeAreasVerdesRoute: typeof ServicioDeMantencionDeAreasVerdesRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  InfoBeneficiosDisenoBiofilicoProductividadRoute: typeof InfoBeneficiosDisenoBiofilicoProductividadRoute
  InfoEndoterapiaVegetalAlternativaEcologicaRoute: typeof InfoEndoterapiaVegetalAlternativaEcologicaRoute
  InfoImportanciaDeAreasVerdesOficinasEmpresasRoute: typeof InfoImportanciaDeAreasVerdesOficinasEmpresasRoute
  InfoImportanciaDesmalezadoControlPlagasEmpresasRoute: typeof InfoImportanciaDesmalezadoControlPlagasEmpresasRoute
  InfoImportanciaFumigacionesPreventivasRoute: typeof InfoImportanciaFumigacionesPreventivasRoute
  InfoImportanciaPodaPreventivaOtonoRoute: typeof InfoImportanciaPodaPreventivaOtonoRoute
  InfoImportanciaRiegoInteligenteEmpresasRoute: typeof InfoImportanciaRiegoInteligenteEmpresasRoute
  InfoMurosVerdesYJardinesVerticalesCorporativosRoute: typeof InfoMurosVerdesYJardinesVerticalesCorporativosRoute
  InfoXerojardineriaPaisajismoSecoCorporativoRoute: typeof InfoXerojardineriaPaisajismoSecoCorporativoRoute
  InfoIndexRoute: typeof InfoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicio-de-mantencion-de-areas-verdes': {
      id: '/servicio-de-mantencion-de-areas-verdes'
      path: '/servicio-de-mantencion-de-areas-verdes'
      fullPath: '/servicio-de-mantencion-de-areas-verdes'
      preLoaderRoute: typeof ServicioDeMantencionDeAreasVerdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile': {
      id: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
      path: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
      fullPath: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
      preLoaderRoute: typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile': {
      id: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
      path: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
      fullPath: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
      preLoaderRoute: typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-paisajismo-residencial-zapallar-chile': {
      id: '/proyecto-paisajismo-residencial-zapallar-chile'
      path: '/proyecto-paisajismo-residencial-zapallar-chile'
      fullPath: '/proyecto-paisajismo-residencial-zapallar-chile'
      preLoaderRoute: typeof ProyectoPaisajismoResidencialZapallarChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-paisajismo': {
      id: '/proyecto-paisajismo'
      path: '/proyecto-paisajismo'
      fullPath: '/proyecto-paisajismo'
      preLoaderRoute: typeof ProyectoPaisajismoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-muro-verde-vertical-vitacura-chile': {
      id: '/proyecto-muro-verde-vertical-vitacura-chile'
      path: '/proyecto-muro-verde-vertical-vitacura-chile'
      fullPath: '/proyecto-muro-verde-vertical-vitacura-chile'
      preLoaderRoute: typeof ProyectoMuroVerdeVerticalVitacuraChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile': {
      id: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
      path: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
      fullPath: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
      preLoaderRoute: typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-habilitacion-terraza-corporativa-las-condes-chile': {
      id: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
      path: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
      fullPath: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
      preLoaderRoute: typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-fumigacion-control-fitosanitario-quilicura-chile': {
      id: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
      path: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
      fullPath: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
      preLoaderRoute: typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-diseno-paisajismo-vial-copec-santiago-chile': {
      id: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
      path: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
      fullPath: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
      preLoaderRoute: typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile': {
      id: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
      path: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
      fullPath: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
      preLoaderRoute: typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial': {
      id: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
      path: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
      fullPath: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
      preLoaderRoute: typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosario': {
      id: '/glosario'
      path: '/glosario'
      fullPath: '/glosario'
      preLoaderRoute: typeof GlosarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-y-construcion-de-sistemas-de-riego': {
      id: '/diseno-y-construcion-de-sistemas-de-riego'
      path: '/diseno-y-construcion-de-sistemas-de-riego'
      fullPath: '/diseno-y-construcion-de-sistemas-de-riego'
      preLoaderRoute: typeof DisenoYConstrucionDeSistemasDeRiegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-y-construccion-de-areas-verdes': {
      id: '/diseno-y-construccion-de-areas-verdes'
      path: '/diseno-y-construccion-de-areas-verdes'
      fullPath: '/diseno-y-construccion-de-areas-verdes'
      preLoaderRoute: typeof DisenoYConstruccionDeAreasVerdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-fitosanitario-y-manejo-de-plagas-areas-verdes': {
      id: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
      path: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
      fullPath: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
      preLoaderRoute: typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Trabajo-poda-tala-emergencia-arauco-quilicura': {
      id: '/Trabajo-poda-tala-emergencia-arauco-quilicura'
      path: '/Trabajo-poda-tala-emergencia-arauco-quilicura'
      fullPath: '/Trabajo-poda-tala-emergencia-arauco-quilicura'
      preLoaderRoute: typeof TrabajoPodaTalaEmergenciaAraucoQuilicuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura': {
      id: '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura'
      path: '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura'
      fullPath: '/Trabajo-poda-preventiva-mall-arauco-san-ignacio-quilicura'
      preLoaderRoute: typeof TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Trabajo-movimiento-macetas-quilicura': {
      id: '/Trabajo-movimiento-macetas-quilicura'
      path: '/Trabajo-movimiento-macetas-quilicura'
      fullPath: '/Trabajo-movimiento-macetas-quilicura'
      preLoaderRoute: typeof TrabajoMovimientoMacetasQuilicuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura': {
      id: '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura'
      path: '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura'
      fullPath: '/Trabajo-movimiento-macetas-arauco-san-ignacio-quilicura'
      preLoaderRoute: typeof TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura': {
      id: '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura'
      path: '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura'
      fullPath: '/Trabajo-despeje-canal-arauco-san-ignacio-quilicura'
      preLoaderRoute: typeof TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Trabajo-delimitador-vegetal-exterior-mall-quilicura': {
      id: '/Trabajo-delimitador-vegetal-exterior-mall-quilicura'
      path: '/Trabajo-delimitador-vegetal-exterior-mall-quilicura'
      fullPath: '/Trabajo-delimitador-vegetal-exterior-mall-quilicura'
      preLoaderRoute: typeof TrabajoDelimitadorVegetalExteriorMallQuilicuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Poda-emergencia-empresa-air-liquide': {
      id: '/Poda-emergencia-empresa-air-liquide'
      path: '/Poda-emergencia-empresa-air-liquide'
      fullPath: '/Poda-emergencia-empresa-air-liquide'
      preLoaderRoute: typeof PodaEmergenciaEmpresaAirLiquideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Paisajismo-jardinera-pallet-mall-quilicura': {
      id: '/Paisajismo-jardinera-pallet-mall-quilicura'
      path: '/Paisajismo-jardinera-pallet-mall-quilicura'
      fullPath: '/Paisajismo-jardinera-pallet-mall-quilicura'
      preLoaderRoute: typeof PaisajismoJardineraPalletMallQuilicuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mantencion-preventiva-contrato-anual-arauco-quilicura': {
      id: '/Mantencion-preventiva-contrato-anual-arauco-quilicura'
      path: '/Mantencion-preventiva-contrato-anual-arauco-quilicura'
      fullPath: '/Mantencion-preventiva-contrato-anual-arauco-quilicura'
      preLoaderRoute: typeof MantencionPreventivaContratoAnualAraucoQuilicuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/': {
      id: '/info/'
      path: '/info'
      fullPath: '/info/'
      preLoaderRoute: typeof InfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/xerojardineria-paisajismo-seco-corporativo': {
      id: '/info/xerojardineria-paisajismo-seco-corporativo'
      path: '/info/xerojardineria-paisajismo-seco-corporativo'
      fullPath: '/info/xerojardineria-paisajismo-seco-corporativo'
      preLoaderRoute: typeof InfoXerojardineriaPaisajismoSecoCorporativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/muros-verdes-y-jardines-verticales-corporativos': {
      id: '/info/muros-verdes-y-jardines-verticales-corporativos'
      path: '/info/muros-verdes-y-jardines-verticales-corporativos'
      fullPath: '/info/muros-verdes-y-jardines-verticales-corporativos'
      preLoaderRoute: typeof InfoMurosVerdesYJardinesVerticalesCorporativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/importancia-riego-inteligente-empresas': {
      id: '/info/importancia-riego-inteligente-empresas'
      path: '/info/importancia-riego-inteligente-empresas'
      fullPath: '/info/importancia-riego-inteligente-empresas'
      preLoaderRoute: typeof InfoImportanciaRiegoInteligenteEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/importancia-poda-preventiva-otono': {
      id: '/info/importancia-poda-preventiva-otono'
      path: '/info/importancia-poda-preventiva-otono'
      fullPath: '/info/importancia-poda-preventiva-otono'
      preLoaderRoute: typeof InfoImportanciaPodaPreventivaOtonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/importancia-fumigaciones-preventivas': {
      id: '/info/importancia-fumigaciones-preventivas'
      path: '/info/importancia-fumigaciones-preventivas'
      fullPath: '/info/importancia-fumigaciones-preventivas'
      preLoaderRoute: typeof InfoImportanciaFumigacionesPreventivasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/importancia-desmalezado-control-plagas-empresas': {
      id: '/info/importancia-desmalezado-control-plagas-empresas'
      path: '/info/importancia-desmalezado-control-plagas-empresas'
      fullPath: '/info/importancia-desmalezado-control-plagas-empresas'
      preLoaderRoute: typeof InfoImportanciaDesmalezadoControlPlagasEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/importancia-de-areas-verdes-oficinas-empresas': {
      id: '/info/importancia-de-areas-verdes-oficinas-empresas'
      path: '/info/importancia-de-areas-verdes-oficinas-empresas'
      fullPath: '/info/importancia-de-areas-verdes-oficinas-empresas'
      preLoaderRoute: typeof InfoImportanciaDeAreasVerdesOficinasEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/endoterapia-vegetal-alternativa-ecologica': {
      id: '/info/endoterapia-vegetal-alternativa-ecologica'
      path: '/info/endoterapia-vegetal-alternativa-ecologica'
      fullPath: '/info/endoterapia-vegetal-alternativa-ecologica'
      preLoaderRoute: typeof InfoEndoterapiaVegetalAlternativaEcologicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/beneficios-diseno-biofilico-productividad': {
      id: '/info/beneficios-diseno-biofilico-productividad'
      path: '/info/beneficios-diseno-biofilico-productividad'
      fullPath: '/info/beneficios-diseno-biofilico-productividad'
      preLoaderRoute: typeof InfoBeneficiosDisenoBiofilicoProductividadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MantencionPreventivaContratoAnualAraucoQuilicuraRoute:
    MantencionPreventivaContratoAnualAraucoQuilicuraRoute,
  PaisajismoJardineraPalletMallQuilicuraRoute:
    PaisajismoJardineraPalletMallQuilicuraRoute,
  PodaEmergenciaEmpresaAirLiquideRoute: PodaEmergenciaEmpresaAirLiquideRoute,
  TrabajoDelimitadorVegetalExteriorMallQuilicuraRoute:
    TrabajoDelimitadorVegetalExteriorMallQuilicuraRoute,
  TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRoute:
    TrabajoDespejeCanalAraucoSanIgnacioQuilicuraRoute,
  TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRoute:
    TrabajoMovimientoMacetasAraucoSanIgnacioQuilicuraRoute,
  TrabajoMovimientoMacetasQuilicuraRoute:
    TrabajoMovimientoMacetasQuilicuraRoute,
  TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRoute:
    TrabajoPodaPreventivaMallAraucoSanIgnacioQuilicuraRoute,
  TrabajoPodaTalaEmergenciaAraucoQuilicuraRoute:
    TrabajoPodaTalaEmergenciaAraucoQuilicuraRoute,
  ContactoRoute: ContactoRoute,
  ControlFitosanitarioYManejoDePlagasAreasVerdesRoute:
    ControlFitosanitarioYManejoDePlagasAreasVerdesRoute,
  DisenoYConstruccionDeAreasVerdesRoute: DisenoYConstruccionDeAreasVerdesRoute,
  DisenoYConstrucionDeSistemasDeRiegoRoute:
    DisenoYConstrucionDeSistemasDeRiegoRoute,
  GlosarioRoute: GlosarioRoute,
  PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute:
    PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute,
  ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute:
    ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute,
  ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute:
    ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute,
  ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute:
    ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute,
  ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute:
    ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute,
  ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute:
    ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute,
  ProyectoMuroVerdeVerticalVitacuraChileRoute:
    ProyectoMuroVerdeVerticalVitacuraChileRoute,
  ProyectoPaisajismoRoute: ProyectoPaisajismoRoute,
  ProyectoPaisajismoResidencialZapallarChileRoute:
    ProyectoPaisajismoResidencialZapallarChileRoute,
  ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute:
    ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute,
  ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute:
    ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute,
  ServicioDeMantencionDeAreasVerdesRoute:
    ServicioDeMantencionDeAreasVerdesRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
  InfoBeneficiosDisenoBiofilicoProductividadRoute:
    InfoBeneficiosDisenoBiofilicoProductividadRoute,
  InfoEndoterapiaVegetalAlternativaEcologicaRoute:
    InfoEndoterapiaVegetalAlternativaEcologicaRoute,
  InfoImportanciaDeAreasVerdesOficinasEmpresasRoute:
    InfoImportanciaDeAreasVerdesOficinasEmpresasRoute,
  InfoImportanciaDesmalezadoControlPlagasEmpresasRoute:
    InfoImportanciaDesmalezadoControlPlagasEmpresasRoute,
  InfoImportanciaFumigacionesPreventivasRoute:
    InfoImportanciaFumigacionesPreventivasRoute,
  InfoImportanciaPodaPreventivaOtonoRoute:
    InfoImportanciaPodaPreventivaOtonoRoute,
  InfoImportanciaRiegoInteligenteEmpresasRoute:
    InfoImportanciaRiegoInteligenteEmpresasRoute,
  InfoMurosVerdesYJardinesVerticalesCorporativosRoute:
    InfoMurosVerdesYJardinesVerticalesCorporativosRoute,
  InfoXerojardineriaPaisajismoSecoCorporativoRoute:
    InfoXerojardineriaPaisajismoSecoCorporativoRoute,
  InfoIndexRoute: InfoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
