/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as ServicioDeMantencionDeAreasVerdesRouteImport } from './routes/servicio-de-mantencion-de-areas-verdes'
import { Route as ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRouteImport } from './routes/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
import { Route as ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRouteImport } from './routes/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
import { Route as ProyectoPaisajismoResidencialZapallarChileRouteImport } from './routes/proyecto-paisajismo-residencial-zapallar-chile'
import { Route as ProyectoPaisajismoRouteImport } from './routes/proyecto-paisajismo'
import { Route as ProyectoMuroVerdeVerticalVitacuraChileRouteImport } from './routes/proyecto-muro-verde-vertical-vitacura-chile'
import { Route as ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRouteImport } from './routes/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
import { Route as ProyectoHabilitacionTerrazaCorporativaLasCondesChileRouteImport } from './routes/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
import { Route as ProyectoFumigacionControlFitosanitarioQuilicuraChileRouteImport } from './routes/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
import { Route as ProyectoDisenoPaisajismoVialCopecSantiagoChileRouteImport } from './routes/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
import { Route as ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRouteImport } from './routes/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
import { Route as PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRouteImport } from './routes/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
import { Route as GlosarioRouteImport } from './routes/glosario'
import { Route as DisenoYConstrucionDeSistemasDeRiegoRouteImport } from './routes/diseno-y-construcion-de-sistemas-de-riego'
import { Route as DisenoYConstruccionDeAreasVerdesRouteImport } from './routes/diseno-y-construccion-de-areas-verdes'
import { Route as ControlFitosanitarioYManejoDePlagasAreasVerdesRouteImport } from './routes/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicioDeMantencionDeAreasVerdesRoute =
  ServicioDeMantencionDeAreasVerdesRouteImport.update({
    id: '/servicio-de-mantencion-de-areas-verdes',
    path: '/servicio-de-mantencion-de-areas-verdes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute =
  ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRouteImport.update({
    id: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile',
    path: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute =
  ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRouteImport.update({
    id: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile',
    path: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoPaisajismoResidencialZapallarChileRoute =
  ProyectoPaisajismoResidencialZapallarChileRouteImport.update({
    id: '/proyecto-paisajismo-residencial-zapallar-chile',
    path: '/proyecto-paisajismo-residencial-zapallar-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoPaisajismoRoute = ProyectoPaisajismoRouteImport.update({
  id: '/proyecto-paisajismo',
  path: '/proyecto-paisajismo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectoMuroVerdeVerticalVitacuraChileRoute =
  ProyectoMuroVerdeVerticalVitacuraChileRouteImport.update({
    id: '/proyecto-muro-verde-vertical-vitacura-chile',
    path: '/proyecto-muro-verde-vertical-vitacura-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute =
  ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRouteImport.update({
    id: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile',
    path: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute =
  ProyectoHabilitacionTerrazaCorporativaLasCondesChileRouteImport.update({
    id: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile',
    path: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute =
  ProyectoFumigacionControlFitosanitarioQuilicuraChileRouteImport.update({
    id: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile',
    path: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute =
  ProyectoDisenoPaisajismoVialCopecSantiagoChileRouteImport.update({
    id: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile',
    path: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute =
  ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRouteImport.update({
    id: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile',
    path: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile',
    getParentRoute: () => rootRouteImport,
  } as any)
const PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute =
  PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRouteImport.update({
    id: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial',
    path: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial',
    getParentRoute: () => rootRouteImport,
  } as any)
const GlosarioRoute = GlosarioRouteImport.update({
  id: '/glosario',
  path: '/glosario',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoYConstrucionDeSistemasDeRiegoRoute =
  DisenoYConstrucionDeSistemasDeRiegoRouteImport.update({
    id: '/diseno-y-construcion-de-sistemas-de-riego',
    path: '/diseno-y-construcion-de-sistemas-de-riego',
    getParentRoute: () => rootRouteImport,
  } as any)
const DisenoYConstruccionDeAreasVerdesRoute =
  DisenoYConstruccionDeAreasVerdesRouteImport.update({
    id: '/diseno-y-construccion-de-areas-verdes',
    path: '/diseno-y-construccion-de-areas-verdes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ControlFitosanitarioYManejoDePlagasAreasVerdesRoute =
  ControlFitosanitarioYManejoDePlagasAreasVerdesRouteImport.update({
    id: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes',
    path: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/control-fitosanitario-y-manejo-de-plagas-areas-verdes': typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRoute
  '/diseno-y-construccion-de-areas-verdes': typeof DisenoYConstruccionDeAreasVerdesRoute
  '/diseno-y-construcion-de-sistemas-de-riego': typeof DisenoYConstrucionDeSistemasDeRiegoRoute
  '/glosario': typeof GlosarioRoute
  '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial': typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute
  '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile': typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute
  '/proyecto-diseno-paisajismo-vial-copec-santiago-chile': typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute
  '/proyecto-fumigacion-control-fitosanitario-quilicura-chile': typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute
  '/proyecto-habilitacion-terraza-corporativa-las-condes-chile': typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute
  '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile': typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute
  '/proyecto-muro-verde-vertical-vitacura-chile': typeof ProyectoMuroVerdeVerticalVitacuraChileRoute
  '/proyecto-paisajismo': typeof ProyectoPaisajismoRoute
  '/proyecto-paisajismo-residencial-zapallar-chile': typeof ProyectoPaisajismoResidencialZapallarChileRoute
  '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile': typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute
  '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile': typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute
  '/servicio-de-mantencion-de-areas-verdes': typeof ServicioDeMantencionDeAreasVerdesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/control-fitosanitario-y-manejo-de-plagas-areas-verdes': typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRoute
  '/diseno-y-construccion-de-areas-verdes': typeof DisenoYConstruccionDeAreasVerdesRoute
  '/diseno-y-construcion-de-sistemas-de-riego': typeof DisenoYConstrucionDeSistemasDeRiegoRoute
  '/glosario': typeof GlosarioRoute
  '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial': typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute
  '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile': typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute
  '/proyecto-diseno-paisajismo-vial-copec-santiago-chile': typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute
  '/proyecto-fumigacion-control-fitosanitario-quilicura-chile': typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute
  '/proyecto-habilitacion-terraza-corporativa-las-condes-chile': typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute
  '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile': typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute
  '/proyecto-muro-verde-vertical-vitacura-chile': typeof ProyectoMuroVerdeVerticalVitacuraChileRoute
  '/proyecto-paisajismo': typeof ProyectoPaisajismoRoute
  '/proyecto-paisajismo-residencial-zapallar-chile': typeof ProyectoPaisajismoResidencialZapallarChileRoute
  '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile': typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute
  '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile': typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute
  '/servicio-de-mantencion-de-areas-verdes': typeof ServicioDeMantencionDeAreasVerdesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/control-fitosanitario-y-manejo-de-plagas-areas-verdes': typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRoute
  '/diseno-y-construccion-de-areas-verdes': typeof DisenoYConstruccionDeAreasVerdesRoute
  '/diseno-y-construcion-de-sistemas-de-riego': typeof DisenoYConstrucionDeSistemasDeRiegoRoute
  '/glosario': typeof GlosarioRoute
  '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial': typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute
  '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile': typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute
  '/proyecto-diseno-paisajismo-vial-copec-santiago-chile': typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute
  '/proyecto-fumigacion-control-fitosanitario-quilicura-chile': typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute
  '/proyecto-habilitacion-terraza-corporativa-las-condes-chile': typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute
  '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile': typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute
  '/proyecto-muro-verde-vertical-vitacura-chile': typeof ProyectoMuroVerdeVerticalVitacuraChileRoute
  '/proyecto-paisajismo': typeof ProyectoPaisajismoRoute
  '/proyecto-paisajismo-residencial-zapallar-chile': typeof ProyectoPaisajismoResidencialZapallarChileRoute
  '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile': typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute
  '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile': typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute
  '/servicio-de-mantencion-de-areas-verdes': typeof ServicioDeMantencionDeAreasVerdesRoute
  '/sobre-nosotros': typeof SobreNosotrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
    | '/diseno-y-construccion-de-areas-verdes'
    | '/diseno-y-construcion-de-sistemas-de-riego'
    | '/glosario'
    | '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
    | '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
    | '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
    | '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
    | '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
    | '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
    | '/proyecto-muro-verde-vertical-vitacura-chile'
    | '/proyecto-paisajismo'
    | '/proyecto-paisajismo-residencial-zapallar-chile'
    | '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
    | '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
    | '/servicio-de-mantencion-de-areas-verdes'
    | '/sobre-nosotros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
    | '/diseno-y-construccion-de-areas-verdes'
    | '/diseno-y-construcion-de-sistemas-de-riego'
    | '/glosario'
    | '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
    | '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
    | '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
    | '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
    | '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
    | '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
    | '/proyecto-muro-verde-vertical-vitacura-chile'
    | '/proyecto-paisajismo'
    | '/proyecto-paisajismo-residencial-zapallar-chile'
    | '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
    | '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
    | '/servicio-de-mantencion-de-areas-verdes'
    | '/sobre-nosotros'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
    | '/diseno-y-construccion-de-areas-verdes'
    | '/diseno-y-construcion-de-sistemas-de-riego'
    | '/glosario'
    | '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
    | '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
    | '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
    | '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
    | '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
    | '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
    | '/proyecto-muro-verde-vertical-vitacura-chile'
    | '/proyecto-paisajismo'
    | '/proyecto-paisajismo-residencial-zapallar-chile'
    | '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
    | '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
    | '/servicio-de-mantencion-de-areas-verdes'
    | '/sobre-nosotros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ControlFitosanitarioYManejoDePlagasAreasVerdesRoute: typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRoute
  DisenoYConstruccionDeAreasVerdesRoute: typeof DisenoYConstruccionDeAreasVerdesRoute
  DisenoYConstrucionDeSistemasDeRiegoRoute: typeof DisenoYConstrucionDeSistemasDeRiegoRoute
  GlosarioRoute: typeof GlosarioRoute
  PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute: typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute
  ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute: typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute
  ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute: typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute
  ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute: typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute
  ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute: typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute
  ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute: typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute
  ProyectoMuroVerdeVerticalVitacuraChileRoute: typeof ProyectoMuroVerdeVerticalVitacuraChileRoute
  ProyectoPaisajismoRoute: typeof ProyectoPaisajismoRoute
  ProyectoPaisajismoResidencialZapallarChileRoute: typeof ProyectoPaisajismoResidencialZapallarChileRoute
  ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute: typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute
  ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute: typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute
  ServicioDeMantencionDeAreasVerdesRoute: typeof ServicioDeMantencionDeAreasVerdesRoute
  SobreNosotrosRoute: typeof SobreNosotrosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicio-de-mantencion-de-areas-verdes': {
      id: '/servicio-de-mantencion-de-areas-verdes'
      path: '/servicio-de-mantencion-de-areas-verdes'
      fullPath: '/servicio-de-mantencion-de-areas-verdes'
      preLoaderRoute: typeof ServicioDeMantencionDeAreasVerdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile': {
      id: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
      path: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
      fullPath: '/proyecto-poda-preventiva-silvicultura-arbolado-quilicura-chile'
      preLoaderRoute: typeof ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile': {
      id: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
      path: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
      fullPath: '/proyecto-paisajismo-seco-reconversion-hidrica-quilicura-chile'
      preLoaderRoute: typeof ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-paisajismo-residencial-zapallar-chile': {
      id: '/proyecto-paisajismo-residencial-zapallar-chile'
      path: '/proyecto-paisajismo-residencial-zapallar-chile'
      fullPath: '/proyecto-paisajismo-residencial-zapallar-chile'
      preLoaderRoute: typeof ProyectoPaisajismoResidencialZapallarChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-paisajismo': {
      id: '/proyecto-paisajismo'
      path: '/proyecto-paisajismo'
      fullPath: '/proyecto-paisajismo'
      preLoaderRoute: typeof ProyectoPaisajismoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-muro-verde-vertical-vitacura-chile': {
      id: '/proyecto-muro-verde-vertical-vitacura-chile'
      path: '/proyecto-muro-verde-vertical-vitacura-chile'
      fullPath: '/proyecto-muro-verde-vertical-vitacura-chile'
      preLoaderRoute: typeof ProyectoMuroVerdeVerticalVitacuraChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile': {
      id: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
      path: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
      fullPath: '/proyecto-mantencion-areas-verdes-industriales-san-ignacio-chile'
      preLoaderRoute: typeof ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-habilitacion-terraza-corporativa-las-condes-chile': {
      id: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
      path: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
      fullPath: '/proyecto-habilitacion-terraza-corporativa-las-condes-chile'
      preLoaderRoute: typeof ProyectoHabilitacionTerrazaCorporativaLasCondesChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-fumigacion-control-fitosanitario-quilicura-chile': {
      id: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
      path: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
      fullPath: '/proyecto-fumigacion-control-fitosanitario-quilicura-chile'
      preLoaderRoute: typeof ProyectoFumigacionControlFitosanitarioQuilicuraChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-diseno-paisajismo-vial-copec-santiago-chile': {
      id: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
      path: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
      fullPath: '/proyecto-diseno-paisajismo-vial-copec-santiago-chile'
      preLoaderRoute: typeof ProyectoDisenoPaisajismoVialCopecSantiagoChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile': {
      id: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
      path: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
      fullPath: '/proyecto-diseno-habilitacion-piscina-entorno-chicureo-chile'
      preLoaderRoute: typeof ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial': {
      id: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
      path: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
      fullPath: '/poda-tala-y-transplante-profesional-de-arbolado-urbano-comercial'
      preLoaderRoute: typeof PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glosario': {
      id: '/glosario'
      path: '/glosario'
      fullPath: '/glosario'
      preLoaderRoute: typeof GlosarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-y-construcion-de-sistemas-de-riego': {
      id: '/diseno-y-construcion-de-sistemas-de-riego'
      path: '/diseno-y-construcion-de-sistemas-de-riego'
      fullPath: '/diseno-y-construcion-de-sistemas-de-riego'
      preLoaderRoute: typeof DisenoYConstrucionDeSistemasDeRiegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-y-construccion-de-areas-verdes': {
      id: '/diseno-y-construccion-de-areas-verdes'
      path: '/diseno-y-construccion-de-areas-verdes'
      fullPath: '/diseno-y-construccion-de-areas-verdes'
      preLoaderRoute: typeof DisenoYConstruccionDeAreasVerdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-fitosanitario-y-manejo-de-plagas-areas-verdes': {
      id: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
      path: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
      fullPath: '/control-fitosanitario-y-manejo-de-plagas-areas-verdes'
      preLoaderRoute: typeof ControlFitosanitarioYManejoDePlagasAreasVerdesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ControlFitosanitarioYManejoDePlagasAreasVerdesRoute:
    ControlFitosanitarioYManejoDePlagasAreasVerdesRoute,
  DisenoYConstruccionDeAreasVerdesRoute: DisenoYConstruccionDeAreasVerdesRoute,
  DisenoYConstrucionDeSistemasDeRiegoRoute:
    DisenoYConstrucionDeSistemasDeRiegoRoute,
  GlosarioRoute: GlosarioRoute,
  PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute:
    PodaTalaYTransplanteProfesionalDeArboladoUrbanoComercialRoute,
  ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute:
    ProyectoDisenoHabilitacionPiscinaEntornoChicureoChileRoute,
  ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute:
    ProyectoDisenoPaisajismoVialCopecSantiagoChileRoute,
  ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute:
    ProyectoFumigacionControlFitosanitarioQuilicuraChileRoute,
  ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute:
    ProyectoHabilitacionTerrazaCorporativaLasCondesChileRoute,
  ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute:
    ProyectoMantencionAreasVerdesIndustrialesSanIgnacioChileRoute,
  ProyectoMuroVerdeVerticalVitacuraChileRoute:
    ProyectoMuroVerdeVerticalVitacuraChileRoute,
  ProyectoPaisajismoRoute: ProyectoPaisajismoRoute,
  ProyectoPaisajismoResidencialZapallarChileRoute:
    ProyectoPaisajismoResidencialZapallarChileRoute,
  ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute:
    ProyectoPaisajismoSecoReconversionHidricaQuilicuraChileRoute,
  ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute:
    ProyectoPodaPreventivaSilviculturaArboladoQuilicuraChileRoute,
  ServicioDeMantencionDeAreasVerdesRoute:
    ServicioDeMantencionDeAreasVerdesRoute,
  SobreNosotrosRoute: SobreNosotrosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
